<#import "blocks/default.ftlh" as c>
<#include "blocks/noimage.ftlh">


<@c.page>
    <div class="row">
        <div class="col-md-6 offset-md-3 mt-5">
            <div class="card">
                <div class="card-header">
                    <h3 class="text-center">403 Forbidden</h3>
                </div>
                <div class="card-body">
                    <p class="text-center">Sorry, you do not have permission to access this page.</p>
                </div>
            </div>
        </div>
    </div>
</@c.page>